Iter9
kindenko/go-shorterurl pull request #10
Opened 2023-07-03 14:51 UTC by kindenko

2023-07-03 21:05 UTC, valentinsoe requested changes
Спасибо за работу.
Все написано просто и аккуратно.
Замечания расписал по коду. Из важного - нет зависимости сжатия ответа от Content-Type

2023-07-03 21:05 UTC, valentinsoe commented on cmd/shortener/main.go
> +	_ "flag"
А тут нужен пакет flag? Может лучше его удалить совсем?

2023-07-03 21:05 UTC, valentinsoe commented on cmd/shortener/main.go
> +	_ "github.com/kindenko/go-shorterurl/internal/app/storage"
Аналогично с предыдущим комментарием.

2023-07-03 21:05 UTC, valentinsoe commented on config/config.go
> +	flag.StringVar(&cfq.FilePATH, "f", "/tmp/short-url-db.json", "It's a FilePATH")
Занудство. Описание параметров стоит писать более понятными.

2023-07-03 21:05 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +	fmt.Println(a.cfg.FilePATH)
У нас уже есть логгер,а это отладочный вывод. Лучше такое не оставлять в коде.

2023-07-03 21:05 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +	fileStorage := storage.NewFileStorage()
Аккуратнее бы выглядело, если бы id и url были переданы в инициализатор в виде параметров.

2023-07-03 21:05 UTC, valentinsoe commented on internal/app/handlers/handlers.go
>  func (a *Handlers) PostHandler(w http.ResponseWriter, r *http.Request) {
Почему handlers переменную зовут a? Хотя бы h :)

2023-07-03 21:05 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		fileStorage := storage.NewFileStorage()
Эта часть кода дублируется с предыдущей функцией. Стоит вынести ее в отдельную функцию.

2023-07-03 21:05 UTC, valentinsoe commented on internal/app/zip/gzip.go
> +			cw := newCompressWriter(w)
В задании явным образом указано, что сжимать ответ надо только для конкретных Content-Type

2023-07-03 21:05 UTC, valentinsoe commented on cmd/shortener/main.go
> +	// подправить midleware
Да, будет аккуратнее просто добавить middleware для всего роутера, чем оборачивать каждый отдельный handler.

2023-07-11 20:24 UTC, valentinsoe requested changes
Спасибо за исправления.
Все стало "аккуратнее".
Из существенных замечаний - обработка заголовков при сжатии ответа.

2023-07-11 20:24 UTC, valentinsoe commented on internal/app/logger/logger.go
> +// func WithLogging(h http.HandlerFunc) http.HandlerFunc {
Занудство. Такие длинные комментарии лучше подчищать

2023-07-11 20:24 UTC, valentinsoe commented on internal/app/zip/gzip.go
> +		contentType := r.Header.Get("Content-Type")
Я извиняюсь за то комментирую ссылкой.
Но пару раз акцентировал на жтом внимание в пачке. Нас интересует Content-Type ответа, а не запроса. Прочитай пожалуйста тред:
https://app.pachca.com/chats/5949547?message=63689392

2023-07-11 20:24 UTC, valentinsoe commented on internal/app/zip/gzip.go
> +		if strings.Contains(r.Header.Get("Content-Encoding"), "gzip") {
Не совсем верно использовать здесь Contains. Нужно использовать обычное сравнение.

2023-07-13 21:33 UTC, valentinsoe requested changes
Спасибо за исправления.
Часть задания все еще не выполнена(проверять заголовок Content-Type ответа).
Если не получается это исправить - есть длинное обсуждение в пачке.
Или например можно настроить middleware compress, входящую в пакет chi.

2023-07-13 21:33 UTC, valentinsoe commented on internal/app/zip/gzip.go
> +			case "gzip":
Здесь как раз прямое совпадение не требуется

2023-07-13 21:33 UTC, valentinsoe commented on internal/app/zip/gzip.go
> +			case "gzip":
Повторю замечание. В задании явно указано, что сжатие ответа должно происходить только для конкретных Content-Type ответа, а не для всех. Этой логики тут все еще нет.

2023-07-14 10:42 UTC, kindenko commented on internal/app/zip/gzip.go
> +			case "gzip":
Кажется со 2 раза понял !!)

2023-07-14 14:30 UTC, valentinsoe approved these changes
Работу принимаю.
Это конечно немного чит, но явно в задании не просили реализовывать сжатие самому.
Рекомендую почитать как эта middleware устроена в chi, многие при самостоятельной реализации испытывали сложности.

2023-07-15 17:22 UTC, merged