Iter13
kindenko/go-shorterurl pull request #14
Opened 2023-08-17 18:39 UTC by kindenko

2023-08-21 14:45 UTC, valentinsoe requested changes
Спасибо за работу!
Написал ряд замечаний.
Большая часть из них не критична, но лучше их исправить, потому что "неаккуратно"

2023-08-21 14:45 UTC, valentinsoe commented on cmd/shortener/interface.go
> +func ee() {
Лишний файл?

2023-08-21 14:45 UTC, valentinsoe commented on internal/app/database/database.go
> +	shortURL := utils.RandString(fullURL)
С точки зрения разделения ответственности - генерировать короткую ссылку в пакете БД - не верно.

2023-08-21 14:45 UTC, valentinsoe commented on internal/app/database/database.go
> +	log.Println("Забрали шорт", short)
Занудство - смешивать в логах русские и англиский сообщения не очень хорошо.

2023-08-21 14:45 UTC, valentinsoe commented on internal/app/database/database.go
> +		_, err = tx.ExecContext(ctx, "insert into "+"shorterurl"+"(short, long) values ($1, $2)", short, v.OriginalURL)
Клеить строку из частей - не стоит:)

2023-08-21 14:45 UTC, valentinsoe commented on internal/app/database/database.go
> +		// костылище, не смог исправить
fmt.Println - не надо смешивать с логами.
И не понял почему этот костыль тут, а не в чтении конфига:)

2023-08-21 14:45 UTC, valentinsoe commented on internal/app/database/database.go
> +	_, err = db.Exec("create table if not exists shorterurl(id serial not null, short text not null not null, long text not null); create unique index on shorterurl (long)")
Занудство. Название полей long/short - не очень удачны, потому что во многих языках это имя зарезервировано за типами данных.

2023-08-21 14:45 UTC, valentinsoe commented on internal/app/handlers/variable.go
Название файла не очень отражает происходящее в файле

2023-08-21 14:45 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +	ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
Не надо порождать новый контекст, стоит воспользоваться существующим из Request

2023-08-21 14:45 UTC, valentinsoe commented on internal/app/handlers/handlers.go
> +		fmt.Println("Batch: failed to marshal response")
Здесь и везде. У нас есть logger, надо использовать его, а не fmt.Println

2023-08-21 14:45 UTC, valentinsoe commented on internal/app/storage/storage.go
> +func (s *storage) Save(full string) (string, error) {
Не понимаю зачем нужна эта "обертка", вокруг разных реализаций. Кажется это лишнее

2023-08-21 14:45 UTC, valentinsoe commented on internal/app/storage/storage.go
> +	case cfg.FilePATH != "/tmp/short-url-db.json":
Это условие неверное. Если кто-то планирует использовать файл по стандартному пути?

2023-08-24 15:34 UTC, merged

2023-08-28 09:21 UTC, xorium commented on internal/app/storage/filestorage.go
> +func (f *File) Ping() error {
[Feedback]
Если смущает, что для файлового хранилища нужно реализовывать сетевой метод Ping, то можно в интерфейсе (пока непоздно) переименовать в IsHealthy - более обобщенное название (ну и поменять название в реализациях дух)