Iter5
kindenko/go-shorterurl pull request #6
Opened 2023-06-12 08:56 UTC by kindenko

2023-06-13 15:18 UTC, valentinsoe requested changes
Спасибо за работу! Ты стараешься соблюдать конвенции по оформлению кода, написал работающий код и прошел все тесты.
Из замечаний - посмотри пожалуйста про то, как в задании указаны приоритеты параметров запуска. Они у тебя не соответсвуют заданию.
Также пока для нашего задания это не критично, но рекомендую подумать на будущее, над тем как более модульно организовать код. Начать стоит с отделения в отдельный модуль "хранилища" сокращенных ссылок и работу не с конкретной реализацией, а с интерфейсом.

2023-06-13 15:18 UTC, valentinsoe commented on cmd/client.go
> +package main
Супер, что написал клиента себе для тестов.
Попрошу его только убрать в отдельную папочку client.
В корне папки cmd не очень принято хранить код приложения.

2023-06-13 15:18 UTC, valentinsoe commented on cmd/shortener/main.go
> +	urls = make(map[string]string)
Кажется urls уже инициализирован чуть выше, второй раз делать этого не нужно.

2023-06-13 15:18 UTC, valentinsoe commented on config/config.go
> +var SetConfig struct {
Мое занудство. А что значит Set в данном названии?

2023-06-13 15:18 UTC, valentinsoe commented on config/config.go
> +
Здесь сделано не совсем по заданию. В такой реализации ключи командной строки будут более приоритетны, чем переменные окружения.
Более того, значение переменных окружения будет затерто значениями по умолчанию.
Странно что тесты это пропускают:)

2023-06-13 15:18 UTC, valentinsoe commented on go.mod
> +module github.com/kindenko/go-shorterurl.git
Лучше все-таки чтобы имя пакета соответствовало ссылке на репозиторий.
Я бы .git убрал:)

2023-06-13 15:18 UTC, valentinsoe commented on cmd/shortener/main.go
> +		if url == "" {
Кажется мы это только что уже проверили:) Можно не повторять проверку.

2023-06-13 15:18 UTC, valentinsoe commented on cmd/shortener/main.go
> +		id := randstring()
Такое имя функции не соответствует конвенциям Go. Правильное имя было бы randString

2023-06-13 15:18 UTC, valentinsoe commented on cmd/shortener/main.go
> +func newPost(w http.ResponseWriter, r *http.Request) {
Название имени функции не очень информативно.
Я бы из имени предполагал, что она создаст некий новый пост. А это обработчик запроса post.
Кажется более логичным будет имя postHandler?

2023-06-13 15:18 UTC, valentinsoe commented on cmd/shortener/main.go
> +	}
Ты проверяешь метод запрос. А что будет, если отправить запрос с другим методом на данный URL?
Корректной реакцией сервера было бы ответить кодом 405 - http.StatusMethodNotAllowed.

2023-06-13 15:18 UTC, valentinsoe commented on cmd/shortener/main.go
> +	if r.Method == http.MethodGet {
Метод запроса за тебя уже проверил роутер chi, можно дополнительно за ним не проверять:)

2023-06-13 15:18 UTC, valentinsoe commented on cmd/shortener/main.go
> +func randstring() string {
Занудство на подумать(исправлять не надо)
У такого метода генерации сокращенных ссылок есть 2 проблемы.
1) Присылая одну и ту же ссылку несколько раз мы получим разные сокращения
2) Присылая разные ссылку мы можем получить одинаковую короткую и ее подменить.

2023-06-13 15:18 UTC, valentinsoe commented on cmd/shortener/main_test.go
> +			name: "Test request second url",
В тесты также стоит добавить кейсы с ошибками, а не только успешные.
Например кейс когда запрашиваемоего короткого url нет.
Твоя текущая организация тестов этого не позволяет сделать.

Постараюсь объяснить коротко в чем проблема. Каждый твой тест делает 2 действия. Он создает новый короткий url и пытается прочесть его обратно. Это отличный интеграционный тест:)
Но из него сложно будет понять, какая часть сломалась - запись или чтение?
Поэтому начинать покрывать тесты обычно начинаеют с unit-тестов. Которые проверяют строго одну функцию.
Для функции get код такого теста может выглядеть так(пишу псевдо-go-кодом)
url = map[string]string{ "test-short-url": "test-long-url"}
result = client.get("test-short-url")
assert(result, "test-long-url")

Надеюсь, что понятно. Если нет, присылай повторно на ревью и вопросы напиши тут в комментариях.

2023-06-14 07:00 UTC, kindenko commented on config/config.go
> +var SetConfig struct {
Set - сокращенно settings )
Подумал так лучше будет
Могу переименовать

2023-06-14 07:09 UTC, kindenko commented on cmd/shortener/main.go
> +func newPost(w http.ResponseWriter, r *http.Request) {
Да, полностью согласен 
Оставил NewPost после того как переписал на chi и не изменил перед последним коммитом
Спасибо :)

2023-06-14 19:57 UTC, valentinsoe commented on config/config.go
> +var SetConfig struct {
SettingsConfig кажется маслом масляным:)
В моей картине мира Settings - это то, что может меняться по ходу работы приложения(пользователь в интерфейсе или через API что-то поменял).
А Config это то, что считалось при старте из окружения, параметров, файла и т.д.
Set - часто используется как "множество" или глагол "устанавливать". Не самое удачное сокращение для Settings.

2023-06-17 07:43 UTC, kindenko commented on cmd/shortener/main_test.go
> +			name: "Test request second url",
Здравствуйте !
Извините, только добрался до "рефакторинга")

Я столкнулся с проблемой, что при запуске функции и получении короткой ссылки при следующих запусках затирает эту переменную "var urls = make(map[string]string)", поэтому тесты я сделал итерационно чтобы пока есть эта переменная которая содержит сокращенную ссылку из Post функции могла сразу же проверить ее на Get функции. 

Можете указать что я не так сделал чтобы провести тесты как вы указали ?

2023-06-17 17:09 UTC, valentinsoe commented on cmd/shortener/main_test.go
> +			name: "Test request second url",
Чтобы тесты были более независимы - инициализация хранилища не должна быть частью теста.
Ну то есть для тестов создания сокращенной ссылки проблем нет.
А в тестах на проверку получения из сокращенной ссылки полной - нужно в каждом тесте заново инициализировать хранилище.
То есть "начальное" состояние хранилища должно быть частью тест-кейса. Заполнять его должны не другие тесты, а сам тест(в создании теста иметь urls = map[string][string]{"short": "long" } )

2023-06-21 07:38 UTC, valentinsoe commented on config/config.go
> +	a := &AppConfig{}
Не самое удачное имя переменной

2023-06-21 07:41 UTC, valentinsoe commented on internal/app/handlers/handlers_test.go
> +	conf := config.NewCfg()
Нет нужды в коде хендлера конфиг "читать". Если проблема будет в чтении конфига - упадет весь тест. Хотя тестируем мы тут не чтение конфига:)
Можно тут просто сделать config.AppConfig { .... }

2023-06-21 07:49 UTC, valentinsoe approved these changes
Спасибо за правки.
Работу я принимаю, но к следующему инкременту чтение конфига поправь. Сейчас во-первых приоритеты не как в задании, во-вторых просто "опасно".

2023-06-21 07:49 UTC, valentinsoe commented on cmd/shortener/main.go
> +	flag.Parse()
Во-первых, так как flag.Parse() вызван тут, то опять приоритет будет выше даже у значений по умолчанию, чем у переменных окружения.
Потому что в config.NewCfg ты только определил флаги, прочитал переменные окружения. А тут перетрешь их:)
Во-вторых, тут есть еще интересный момент. Ты уже в NewHandlers передал conf, а тут его "перечитываешь".  Это будет работать, потому что передаешь не структуру AppConfig, а указатель на нее. Но в целом, если например handlers.NewHandlers бы проводил какую-то обработку конфига, это приводило бы к ошибкам, которые крайне сложно отлавливать.

2023-06-21 07:54 UTC, kindenko commented on cmd/shortener/main.go
> +	flag.Parse()
Спасибо за комменты ,Валентин !

Я что то не так понял из нашего созвона вчера, видимо. Вы говорили лучше явно определять вызов конфига как я и сделал. Проблема с flag.Parse из за того что переменные окружения могут быть не задействованы , правильно ? 

Или все же проблема в самом определении параметров запуска/переменных окружения в файле config.go ?

2023-06-21 08:40 UTC, valentinsoe commented on cmd/shortener/main.go
> +	flag.Parse()
Все правильно. Явно определить вызов конфига ты сделал.
Есть 2 проблемы
1) переменные окружения будут проигнорированы
2) flag.Parse, который модицирует структуру AppConfig вызван после того, как она уже передана в handlers

Обоих зайцев можно убить одним выстрелом:) Перенести вызова flag.Parse в функцию NewCfg между определением флагов и чтением переменных окружения.

2023-06-25 08:30 UTC, merged